<?php

/**
 * @file
 * Primary module hooks for HTML5 Audio module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

/**
 * Implements hook_theme().
 */
function html5_audio_theme($existing, $type, $theme, $path) {
  return [
    'audio_tag' => [
      'variables' => [
        'sources' => NULL,
        'autoplay' => '',
      ],
    ],
  ];
}
